version: '3.1'
services:
  mongo:
    image: mongo
    command: mongod --bind_ip_all
    environment:
      MONGO_INITDB_DATABASE: exerc4b
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./backup:/backup
