version: '3'

services:
    mongodb1:
        image: mongo:4
        restart: always
        container_name: mongodb1
        volumes:
        - mongodata1:/data/db
        expose:
        - "27017"
        ports:
        - "27017:27017"
        entrypoint: [ "/usr/bin/mongod","--replSet", "fm_rsposmit", "--bind_ip_all"]

    mongodb2:
        image: mongo:4
        restart: always
        container_name: mongodb2
        volumes:
        - mongodata2:/data/db
        expose:
        - "27017"
        ports:
        - "27018:27017"
        entrypoint: [ "/usr/bin/mongod","--replSet", "fm_rsposmit", "--bind_ip_all"]
      
    mongodb3:
        image: mongo:4
        restart: always
        container_name: mongodb3
        volumes:
        - mongodata3:/data/db
        expose:
        - "27017"
        ports:
        - "27019:27017"
        entrypoint: [ "/usr/bin/mongod","--replSet", "fm_rsposmit", "--bind_ip_all"]

    mongodb4:
        image: mongo:4
        restart: always
        container_name: mongodb4
        volumes:
        - mongodata4:/data/db
        expose:
        - "27017"
        ports:
        - "27020:27017"
        entrypoint: [ "/usr/bin/mongod","--replSet", "fm_rsposmit", "--bind_ip_all"]


volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  mongodata4:
